application: pydotorg-status
version: 3
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: django
  version: "1.2"

handlers:
- url: /probe
  script: probe.py

- url: /.*
  script: status.py
